name: delivery_app_cliente
description: "App de delivery para clientes con notificaciones push"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4
  
  # Notificaciones Locales
  flutter_local_notifications: ^18.0.1
  
  # Utilidades
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  # Geolocalización
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  permission_handler: ^11.3.1

  # Imágenes
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # Pagos
  flutter_stripe: ^9.2.0
  webview_flutter: ^4.4.2
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.5.6

  # Utilidades
  share_plus: ^10.1.2  
  provider: ^6.1.1
  url_launcher: ^6.3.1
  http: ^1.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Uncomment the following line to add fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic